name = "Silver Age+"
author = "gameo7"
version = "1.0.0+mc26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce06611372f9a6131170136320fc1aede2480dc51f4949dff4495fcdd5c71fde"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
