name = "Silver Age+"
author = "gameo7"
version = "1.0.0+mc26.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d4733b84e8c9f2eab78330f1db353195ae8788b7bb224511955507bc419aced"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
