name = "Silver Age+"
author = "gameo7"
version = "1.0.0+mc1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b96c31e8a758f0757cda1a111ee4bf7be39bded34cbfd9c313abdeed05d5d1f1"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
