name = "Silver Age+"
author = "gameo7"
version = "1.0.0+mc1.21.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59774cc9dcecb6f58ce0be7492f8cd6087fdba4a596709aee1ce1fdd23425337"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
